### ISSUE TITLE
External ID not found in the system: website.assets_frontend

### ISSUE THREAD

**Issue by nathanbangwa243** [sdegueldre/snippets-oxp-2020#1]
Hello friends

I was following the training session ([follow the link](https://www.youtube.com/watch?v=mA4WECek70w)), and at the same time, I was coding a component (snippet) for the website.

but I got an error **_ValueError: External ID not found in the system: website.assets_frontend._**

At first I thought I was wrong in the code, but when I took the code of the training session I noticed that there was the same error.

**_At the time of writing the bug is solved, well let's say I first found the solution before reporting the problem._**
![image](https://user-images.githubusercontent.com/33934115/147642306-96d92a43-cedc-433b-9d56-88871871790d.png)

**Comment by sdegueldre** [comment]
As you mentioned in your pull request, this issue is caused by the changes to the asset system. While your pull request does fix the problem in odoo 15, this repository is meant to be a companion to the talk, and many things have changed since odoo 14, this is not really meant as a guide or as documentation that will stay up to date, but as a snapshot in time on how to do this in version 14. So I don't think this issue is valid considering the objective of this repo (ie I don't want to fix it because it works as intended in the version for which it was designed)

If anyone stumbles upon this issue feel free to take a look at pull request #2 which contains an outline of what to do to achieve the same thing in odoo 15+.
